#!/bin/bash
#
readonly TABLES=(
    "pf_pessoas.pessoas fields.id-cpf-nome-nascimento-sexo-nome_mae-cpf_mae-nome_pai-geracao-signo-estado_civil-nacionalidade-rg-data_origem-rg_orgao_emissor-rg_uf_emissor-id_serasa-origem-cpf_basico-updated_at-created_at constratins.id indexes.id-cpf-cpf_basico-updated_at-id_serasa-nascimento-nome_sexo triggers.set_updated_at"
    "pf_cbo.cbo fields.cpf-cbo-passivel_profissao-origem-data_origem-updated_at-renda-cpts_serie-cpts_numero-classe-pis-id-created_at constraints.id indexes.id-cpf-cbo"
    "pf_emails.emails fields.cpf-email-origem-data_origem-updated_at-id-created_at constranints.id indexes.id-cpf-email triggers.set_updated_at"
    "pf_telefones.telefones fields.cpf-telefone-tipo-localization-whatsapp-score_media-total_calls-updated_at-created_at constraints.id indexes.cpf-status triggers.set_updated_at"
    "pf_escolaridade.escolaridade fields.id-cpf-escolaridade-origem-data_origem-updated_at-created_at indexes.id-cpf.updated_at constraints.cpf triggers.set_updated_at"
    "pf_score.score fields.id-cpf-score-faixa_score-origem-data_origem-updated_at-created_at indexes constraints triggers"
    "pf_capacidade_pagamento.capacidade_pagamento"
    "pf_banco_gov.banco_gov"
    "pf_bolsa_familia.bolsa_familia"
    "pf_classe_social.classe_social"
    "pf_carteira_trabalho.carteira_trabalho"
    "pf_enderecos.enderecos"
    "pf_fgts.fgts fields indexes.id.cpf constraints.id"
    "pf_governos.governos"
    "pf_imoveis_ibge.imoveis_ibge"
    "pf_modelo_analitico_credito.modelo_analitico_credito"
    "pf_nacionalidade.nacionalidade"
    "pf_obitos.obitos"
    "pf_persona_demografica.persona_demografica"
    "pf_propensao_pagamento.propensao_pagamento"
    "pf_renda.renda"
    "pf_pis.pis"
    "pf_poder_aquisitivo.poder_aquisitivo"
    "pf_politicamente_exposta.politicamente_exposta"
    "pf_score_digital.score_digital"
    "pf_situacao_receita.situacao_receita"
    "pf_titulo_eleitor.titulo_eleitor"
    "pf_triagem_risco.triagem_risco"
    "pf_veiculos.veiculos"
    "pf_vinculo_empregaticio.vinculo_empregaticio"
    "pf_vinculos_familiares.vinculos_familiares"
)